import React, {Component} from 'react'
import {Link } from 'react-router-dom';
import './HomePage.css'
import STORE from '../../../STORE'
/* import Carousel from '../../../Utils/Carousel' */

class HomePage extends Component {
    constructor(props){
        super(props);
        this.state = {
            loggedUserId: this.props.loggedUserId,
            loggedUser_id: this.props.loggedUser_id || 1,
        }
	}
    render(){
        const {testUsers, testImages, testMatches, testConvos} = STORE.makeThingsFixtures()
        

        const userConvos = testConvos.filter(convo => convo.user1_id === testUsers[this.state.loggedUser_id-1].id || convo.user2_id === testUsers[this.state.loggedUser_id-1].id )

        const userMatchesTotal = testMatches.filter(match => match.user1_id === testUsers[this.state.loggedUser_id-1].id)
        
        const userMatches = userMatchesTotal.filter(match => match.user1_bool === false) 
        //as long as user1 hasnt accepted keep invite in this list
        return(
            <>
                <span>Welcome back, <h1>{testUsers[this.state.loggedUser_id-1].firstName}!</h1></span>






                {/* <button onClick={e => console.log(userMatchesTotal)}>testy</button> */}
                <div className="home-div display-pic-sec">
                    <img className='pic' src={testImages[0].image} alt="test" />     
                 
                </div>
                {/* <Carousel loggedUser_id={this.state.loggedUserId}/> */}






                <div>
                    <Link to="/search"><button className="search-now">Search Now!</button></Link>
                </div>
                      <Link to="/profile/1">profile preview</Link>  
                <div className="home-div active convos">
                    <h2>Convos</h2>
                    <p>conversation table in db is searched, rows marked with 'validity' and user comments from logged in user_id are listed here as ordered list of links.</p>
                    <ul>
                        {userConvos.map((convo, index)=>
                            <li key={index} ><Link to={`/convo/${convo.user2_id}`}>{testUsers[convo.id].firstName +' '+ testUsers[convo.id].lastName}</Link></li>
                        )}
                    </ul>
                </div>
                <div className="home-div pending-invites">
                    <h2>invites</h2>
                    <p>Invites from users that like your place! list generated by filtering matches where one user has not accepted</p>
                    <ul>
                        {userMatches.map((match, index)=>
                            <li key={index} ><Link to={`/profile/${match.user2_id}`}>{testUsers[match.id].firstName +' '+ testUsers[match.id].lastName  }</Link></li>
                        )}
                    </ul>
                </div>
            </>
        )
    }
}

export default HomePage;